//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_items
    {
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string item_name_arabic { get; set; }
        public string description { get; set; }
        public Nullable<decimal> unit { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image_path { get; set; }
        public string image_path1 { get; set; }
        public string other_details { get; set; }
        public string category { get; set; }
        public string category_image_path { get; set; }
        public string currency { get; set; }
        public int status { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
