//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_delivery_request
    {
        public int request_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string customer_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<decimal> items_count { get; set; }
        public Nullable<decimal> net_amount { get; set; }
        public Nullable<System.DateTime> request_time { get; set; }
        public string other_details { get; set; }
        public int status { get; set; }
    }
}
