//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_complaint
    {
        public int complaint_id { get; set; }
        public Nullable<System.DateTime> complaint_date { get; set; }
        public string customer_name { get; set; }
        public string mobile { get; set; }
        public Nullable<int> userid { get; set; }
        public string email { get; set; }
        public string message { get; set; }
        public string complaint_type { get; set; }
        public Nullable<int> status { get; set; }
    }
}
