//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_transaction
    {
        public long transaction_id { get; set; }
        public string referance_id { get; set; }
        public int customer_id { get; set; }
        public string customer_ip { get; set; }
        public System.DateTime app_date { get; set; }
        public int offer_id { get; set; }
        public decimal amount { get; set; }
        public string offer_name { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string gateway_name { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> amount_received { get; set; }
        public string payment_reference_id { get; set; }
        public string payment_mode { get; set; }
        public string status_text { get; set; }
        public string response { get; set; }
        public string app_type { get; set; }
        public Nullable<int> daily_collection_id { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
