//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class betaskdbEntitiesAPP : DbContext
    {
        public betaskdbEntitiesAPP()
            : base("name=betaskdbEntitiesAPP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_complaint> app_complaint { get; set; }
        public virtual DbSet<app_delivery_request> app_delivery_request { get; set; }
        public virtual DbSet<app_delivery_request_items> app_delivery_request_items { get; set; }
        public virtual DbSet<app_items> app_items { get; set; }
        public virtual DbSet<app_transaction> app_transaction { get; set; }
        public virtual DbSet<building> building { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customer_aggrement> customer_aggrement { get; set; }
        public virtual DbSet<customer_aggrement_temp> customer_aggrement_temp { get; set; }
        public virtual DbSet<customer_division> customer_division { get; set; }
        public virtual DbSet<customer_temp> customer_temp { get; set; }
        public virtual DbSet<customer_upload> customer_upload { get; set; }
        public virtual DbSet<daily_collection> daily_collection { get; set; }
        public virtual DbSet<default_values> default_values { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<delivery_book> delivery_book { get; set; }
        public virtual DbSet<delivery_item_summary> delivery_item_summary { get; set; }
        public virtual DbSet<delivery_items> delivery_items { get; set; }
        public virtual DbSet<delivery_return> delivery_return { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<mail_settings> mail_settings { get; set; }
        public virtual DbSet<route> route { get; set; }
        public virtual DbSet<route_group> route_group { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<tax_setting> tax_setting { get; set; }
        public virtual DbSet<uom_setting> uom_setting { get; set; }
        public virtual DbSet<coupon> coupon { get; set; }
        public virtual DbSet<coupon_leaf> coupon_leaf { get; set; }
        public virtual DbSet<offer> offer { get; set; }
    
        public virtual ObjectResult<RPT_CollectionStatus_Result> RPT_CollectionStatus(Nullable<System.DateTime> delivery_date)
        {
            var delivery_dateParameter = delivery_date.HasValue ?
                new ObjectParameter("delivery_date", delivery_date) :
                new ObjectParameter("delivery_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_CollectionStatus_Result>("RPT_CollectionStatus", delivery_dateParameter);
        }
    
        public virtual ObjectResult<RPT_DeliveryReturnStatus_Result> RPT_DeliveryReturnStatus(Nullable<System.DateTime> delivery_date)
        {
            var delivery_dateParameter = delivery_date.HasValue ?
                new ObjectParameter("delivery_date", delivery_date) :
                new ObjectParameter("delivery_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_DeliveryReturnStatus_Result>("RPT_DeliveryReturnStatus", delivery_dateParameter);
        }
    
        public virtual ObjectResult<RPT_DeliveryStatus_Result> RPT_DeliveryStatus(Nullable<System.DateTime> delivery_date)
        {
            var delivery_dateParameter = delivery_date.HasValue ?
                new ObjectParameter("delivery_date", delivery_date) :
                new ObjectParameter("delivery_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_DeliveryStatus_Result>("RPT_DeliveryStatus", delivery_dateParameter);
        }
    }
}
