//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_leaf
    {
        public int leaf_id { get; set; }
        public int coupon_id { get; set; }
        public long leaf_number { get; set; }
        public decimal leaf_rate { get; set; }
        public string remarks { get; set; }
        public System.DateTime issue_date { get; set; }
        public Nullable<System.DateTime> redeem_date { get; set; }
        public int status { get; set; }
    
        public virtual coupon coupon { get; set; }
        public virtual status status1 { get; set; }
    }
}
