//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_temp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_temp()
        {
            this.customer_aggrement_temp = new HashSet<customer_aggrement_temp>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string pobox { get; set; }
        public string remarks { get; set; }
        public string trn { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string route { get; set; }
        public int status { get; set; }
        public string payment_mode { get; set; }
        public string delivery_interval { get; set; }
        public Nullable<System.DateTime> saved_time { get; set; }
        public string building_name { get; set; }
        public string area { get; set; }
        public string apartment { get; set; }
        public Nullable<int> employee_id { get; set; }
        public int new_customer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_aggrement_temp> customer_aggrement_temp { get; set; }
    }
}
