//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_aggrement_temp
    {
        public int customer_aggrement_temp_id { get; set; }
        public int customer_temp_id { get; set; }
        public int item_id { get; set; }
        public decimal max_qty { get; set; }
        public decimal unit_price { get; set; }
        public int status { get; set; }
        public int is_tax_included { get; set; }
    
        public virtual customer_temp customer_temp { get; set; }
        public virtual item item { get; set; }
    }
}
