//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_division
    {
        public int division_id { get; set; }
        public string division_name { get; set; }
        public int customer_id { get; set; }
        public int status { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual status status1 { get; set; }
    }
}
