//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_upload
    {
        public int document_id { get; set; }
        public string document_type { get; set; }
        public string description { get; set; }
        public int customer_id { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public int employee_id { get; set; }
        public System.DateTime upload_time { get; set; }
        public int status { get; set; }
    
        public virtual customer_upload customer_upload1 { get; set; }
        public virtual customer_upload customer_upload2 { get; set; }
    }
}
