//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_items
    {
        public int delivery_item_id { get; set; }
        public int delivery_id { get; set; }
        public int customer_id { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public decimal rate { get; set; }
        public decimal gross_amount { get; set; }
        public decimal discount { get; set; }
        public decimal total_beforvat { get; set; }
        public decimal vat_amount { get; set; }
        public decimal net_amount { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> delivery_time { get; set; }
        public Nullable<int> sales_id { get; set; }
        public Nullable<System.DateTime> sales_date { get; set; }
        public decimal delivered_qty { get; set; }
        public long delivery_item_id_local { get; set; }
        public Nullable<int> daily_collection_id { get; set; }
        public string delivery_leaf { get; set; }
        public Nullable<int> division_id { get; set; }
        public int is_deposit { get; set; }
        public string payment_mode { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual daily_collection daily_collection { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual item item { get; set; }
        public virtual status status1 { get; set; }
    }
}
