//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_item_summary
    {
        public int delivery_summary_id { get; set; }
        public int delivery_id { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public decimal used_qty { get; set; }
        public decimal balance_qty { get; set; }
        public int status { get; set; }
    
        public virtual delivery delivery { get; set; }
        public virtual item item { get; set; }
        public virtual status status1 { get; set; }
    }
}
