//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.customer_aggrement = new HashSet<customer_aggrement>();
            this.customer_aggrement_temp = new HashSet<customer_aggrement_temp>();
            this.delivery_item_summary = new HashSet<delivery_item_summary>();
            this.delivery_items = new HashSet<delivery_items>();
            this.delivery_return = new HashSet<delivery_return>();
            this.offer = new HashSet<offer>();
        }
    
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string barcode { get; set; }
        public string brand { get; set; }
        public int uom { get; set; }
        public int tax { get; set; }
        public string description { get; set; }
        public decimal cost { get; set; }
        public decimal purchase_rate { get; set; }
        public decimal sale_rate { get; set; }
        public decimal opening_stock { get; set; }
        public int rawmeterial { get; set; }
        public int sellable { get; set; }
        public int stockable { get; set; }
        public int status { get; set; }
        public decimal Stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_aggrement> customer_aggrement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_aggrement_temp> customer_aggrement_temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_item_summary> delivery_item_summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_items> delivery_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_return> delivery_return { get; set; }
        public virtual status status1 { get; set; }
        public virtual tax_setting tax_setting { get; set; }
        public virtual uom_setting uom_setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offer> offer { get; set; }
    }
}
