//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.APP.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public int offer_id { get; set; }
        public string offer_name { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public decimal amount { get; set; }
        public string category { get; set; }
        public decimal price_range_base_from { get; set; }
        public decimal price_range_base_to { get; set; }
        public decimal price_range_from { get; set; }
        public decimal price_range_to { get; set; }
        public decimal rate_exclude_vat { get; set; }
        public decimal vat { get; set; }
        public decimal rate_include_vat { get; set; }
        public string remarks { get; set; }
        public System.DateTime added_on { get; set; }
        public int status { get; set; }
    
        public virtual item item { get; set; }
    }
}
