//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskAPI.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_asset
    {
        public int customer_asset_id { get; set; }
        public int customer_id { get; set; }
        public int item_id { get; set; }
        public System.DateTime delivery_date { get; set; }
        public string delivery_type { get; set; }
        public decimal qty { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string other_details { get; set; }
        public int status { get; set; }
        public string barcode { get; set; }
        public Nullable<int> customer_aggrement_id { get; set; }
        public string remarks { get; set; }
        public System.DateTime updated_on { get; set; }
        public Nullable<System.DateTime> agreement_from { get; set; }
        public Nullable<System.DateTime> agreement_to { get; set; }
        public string agreement_no { get; set; }
        public int monthly_purchase { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual item item { get; set; }
        public virtual customer customer { get; set; }
    }
}
