//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskAPI.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class do_sales_item
    {
        public int do_item_id { get; set; }
        public int do_id { get; set; }
        public long sales_id { get; set; }
        public string do_number { get; set; }
        public decimal gross_amount { get; set; }
        public decimal total_discount { get; set; }
        public decimal total_beforevat { get; set; }
        public decimal total_vat { get; set; }
        public decimal net_amount { get; set; }
        public int status { get; set; }
    
        public virtual do_sales do_sales { get; set; }
        public virtual sales sales { get; set; }
    }
}
