//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskAPI.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class route_group
    {
        public int route_group_id { get; set; }
        public int route_id { get; set; }
        public int sub_route_id { get; set; }
        public int Status { get; set; }
    
        public virtual route route { get; set; }
    }
}
