//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskAPI.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales()
        {
            this.do_sales_item = new HashSet<do_sales_item>();
            this.sales_item = new HashSet<sales_item>();
        }
    
        public long sales_id { get; set; }
        public System.DateTime sales_date { get; set; }
        public string sales_number { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> sales_order { get; set; }
        public string payment_mode { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_no { get; set; }
        public decimal gross_amount { get; set; }
        public decimal total_discount { get; set; }
        public decimal total_beforevat { get; set; }
        public decimal total_vat { get; set; }
        public decimal roundup { get; set; }
        public decimal net_amount { get; set; }
        public decimal cash_paid { get; set; }
        public decimal balance_amount { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
        public string do_number { get; set; }
        public Nullable<int> do_id { get; set; }
        public Nullable<long> collection_id { get; set; }
        public string delivery_leaf { get; set; }
        public Nullable<int> division_id { get; set; }
        public int old_leaf_count { get; set; }
        public Nullable<int> route_id { get; set; }
        public string lpo_number { get; set; }
        public string payment_terms { get; set; }
    
        public virtual customer_division customer_division { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual do_sales do_sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<do_sales_item> do_sales_item { get; set; }
        public virtual route route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_item> sales_item { get; set; }
        public virtual status status1 { get; set; }
        public virtual customer customer { get; set; }
    }
}
