//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskAPI.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_settings
    {
        public int settings_id { get; set; }
        public string wallet_prefix { get; set; }
        public int auto_wallet_generation { get; set; }
        public int min_wallet_length { get; set; }
        public decimal tax_on_recharge { get; set; }
        public int default_item_id { get; set; }
        public int status { get; set; }
        public int allowed_backdate { get; set; }
        public int hide_do { get; set; }
        public int pdc_enable { get; set; }
        public System.DateTime software_startdate { get; set; }
        public string cloud_url { get; set; }
        public int empty_bottle_item_id { get; set; }
        public bool view_loading_in_dsr { get; set; }
        public System.DateTime loading_start_date { get; set; }
    }
}
