//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_transaction_cheque
    {
        public int cheque_id { get; set; }
        public long account_transaction_id { get; set; }
        public int account_transaction_number { get; set; }
        public string cheque_number { get; set; }
        public System.DateTime cheque_date { get; set; }
        public string bank { get; set; }
        public string other_details { get; set; }
        public int status { get; set; }
    
        public virtual account_transaction account_transaction { get; set; }
        public virtual status status1 { get; set; }
    }
}
