//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account_transaction()
        {
            this.account_transaction_cheque = new HashSet<account_transaction_cheque>();
            this.cost_center_transaction = new HashSet<cost_center_transaction>();
        }
    
        public long account_transaction_id { get; set; }
        public int transaction_number { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string transaction_type { get; set; }
        public int ledger_id { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
        public string narration { get; set; }
        public Nullable<long> transaction_type_id { get; set; }
        public string voucher_number { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> added_time { get; set; }
        public Nullable<System.DateTime> reconcil_date { get; set; }
        public string reference_id { get; set; }
        public Nullable<int> route_id { get; set; }
    
        public virtual account_ledger account_ledger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_transaction_cheque> account_transaction_cheque { get; set; }
        public virtual route route { get; set; }
        public virtual status status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cost_center_transaction> cost_center_transaction { get; set; }
    }
}
