//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string description { get; set; }
        public string tin { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string email { get; set; }
        public string pobox { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string web { get; set; }
        public Nullable<int> status { get; set; }
        public string cloud_connection { get; set; }
        public System.DateTime financial_from_date { get; set; }
        public System.DateTime financial_to_date { get; set; }
        public string whatsapp { get; set; }
        public string facebook { get; set; }
        public string Instagram { get; set; }
        public string twitter { get; set; }
    
        public virtual status status1 { get; set; }
    }
}
