//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost_center_transaction
    {
        public int entry_id { get; set; }
        public int cost_center_id { get; set; }
        public int ledger_id { get; set; }
        public Nullable<long> transaction_id { get; set; }
        public Nullable<int> transaction_number { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
        public int status { get; set; }
        public string reference_id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<long> transaction_type_id { get; set; }
    
        public virtual account_ledger account_ledger { get; set; }
        public virtual account_transaction account_transaction { get; set; }
        public virtual cost_center cost_center { get; set; }
        public virtual status status1 { get; set; }
    }
}
