//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_collection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public daily_collection()
        {
            this.delivery_items = new HashSet<delivery_items>();
        }
    
        public long daily_collection_id { get; set; }
        public Nullable<int> delivery_id { get; set; }
        public int customer_id { get; set; }
        public decimal net_amount { get; set; }
        public decimal collected_amount { get; set; }
        public string payment_mode { get; set; }
        public int employee_id { get; set; }
        public System.DateTime delivery_time { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
        public Nullable<int> daily_collection_id_app { get; set; }
        public string delivery_leaf { get; set; }
        public Nullable<int> division_id { get; set; }
        public int is_deposit { get; set; }
        public int is_refund { get; set; }
        public int old_leaf_count { get; set; }
        public Nullable<int> route_id { get; set; }
    
        public virtual delivery delivery { get; set; }
        public virtual employee employee { get; set; }
        public virtual route route { get; set; }
        public virtual status status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_items> delivery_items { get; set; }
        public virtual customer customer { get; set; }
    }
}
