//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_return
    {
        public int delivery_return_id { get; set; }
        public System.DateTime return_date { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public int customer_id { get; set; }
        public int employee_id { get; set; }
        public int status { get; set; }
        public string remarks { get; set; }
        public int return_type { get; set; }
        public System.DateTime server_time { get; set; }
        public Nullable<int> route_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual item item { get; set; }
        public virtual customer customer { get; set; }
    }
}
