//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_book
    {
        public int delivery_book_id { get; set; }
        public string book_number { get; set; }
        public int employee_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public System.DateTime issue_date { get; set; }
        public string leaf_no { get; set; }
        public Nullable<int> delivery_id { get; set; }
        public Nullable<System.DateTime> redeemed_date { get; set; }
        public int status { get; set; }
        public Nullable<int> route_id { get; set; }
    
        public virtual delivery delivery { get; set; }
        public virtual employee employee { get; set; }
        public virtual route route { get; set; }
        public virtual status status1 { get; set; }
        public virtual customer customer { get; set; }
    }
}
