//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class do_sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public do_sales()
        {
            this.do_sales_item = new HashSet<do_sales_item>();
            this.sales = new HashSet<sales>();
        }
    
        public int do_id { get; set; }
        public System.DateTime do_date { get; set; }
        public int customer_id { get; set; }
        public string do_invoice_number { get; set; }
        public Nullable<int> route_id { get; set; }
        public decimal gross_amount { get; set; }
        public decimal total_discount { get; set; }
        public decimal total_beforevat { get; set; }
        public decimal total_vat { get; set; }
        public decimal net_amount { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
        public decimal amount_paid { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<do_sales_item> do_sales_item { get; set; }
        public virtual route route { get; set; }
        public virtual status status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales> sales { get; set; }
    }
}
