//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.customer_asset = new HashSet<customer_asset>();
            this.daily_collection = new HashSet<daily_collection>();
            this.delivery = new HashSet<delivery>();
            this.delivery_book = new HashSet<delivery_book>();
            this.delivery_return = new HashSet<delivery_return>();
            this.item_damage = new HashSet<item_damage>();
            this.loading = new HashSet<loading>();
            this.privileges = new HashSet<privileges>();
            this.transfer_item = new HashSet<transfer_item>();
        }
    
        public int employee_id { get; set; }
        public string employee_code { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime join_date { get; set; }
        public Nullable<System.DateTime> resign_date { get; set; }
        public string national_id { get; set; }
        public string passport { get; set; }
        public string visa { get; set; }
        public string department { get; set; }
        public string designation { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string nationality { get; set; }
        public string state { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public int status { get; set; }
        public string other_details { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<int> salesman_credit_ledger { get; set; }
        public string vehicle { get; set; }
        public string helper { get; set; }
    
        public virtual account_ledger account_ledger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_asset> customer_asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daily_collection> daily_collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery> delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_book> delivery_book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_return> delivery_return { get; set; }
        public virtual route route { get; set; }
        public virtual status status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_damage> item_damage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loading> loading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<privileges> privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfer_item> transfer_item { get; set; }
    }
}
