//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_transaction
    {
        public long item_transaction_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public int item_id { get; set; }
        public decimal item_cost { get; set; }
        public decimal qty_added { get; set; }
        public decimal qty_reduced { get; set; }
        public decimal closing_stock { get; set; }
        public decimal closing_value { get; set; }
        public string transaction_type { get; set; }
        public Nullable<long> transaction_type_id { get; set; }
        public string narration { get; set; }
        public int status { get; set; }
    
        public virtual item item { get; set; }
        public virtual status status1 { get; set; }
    }
}
