//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class loading
    {
        public int load_id { get; set; }
        public int employee_id { get; set; }
        public int delivery_id { get; set; }
        public System.DateTime load_date { get; set; }
        public string helper { get; set; }
        public string vehicle { get; set; }
        public int item_id { get; set; }
        public decimal old_stock { get; set; }
        public decimal empty { get; set; }
        public decimal damage { get; set; }
        public decimal balance { get; set; }
        public decimal new_load { get; set; }
        public decimal total_load { get; set; }
        public decimal @short { get; set; }
        public decimal extra { get; set; }
        public decimal new_stock { get; set; }
        public decimal offload { get; set; }
        public decimal act_stock { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
        public System.DateTime server_time { get; set; }
    
        public virtual delivery delivery { get; set; }
        public virtual employee employee { get; set; }
        public virtual item item { get; set; }
    }
}
