//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_settings
    {
        public int mail_id { get; set; }
        public string from_mail { get; set; }
        public string password { get; set; }
        public string cc1 { get; set; }
        public string cc2 { get; set; }
        public string bcc1 { get; set; }
        public string bcc2 { get; set; }
        public string smtp_host { get; set; }
        public int enable_ssl { get; set; }
        public int smtp_port { get; set; }
        public int smtp_timeout { get; set; }
        public int smtp_use_deafaultcredential { get; set; }
        public string mail_subject { get; set; }
        public string to_mail { get; set; }
    }
}
