//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdc
    {
        public int pdc_id { get; set; }
        public System.DateTime doc_date { get; set; }
        public string cheque_number { get; set; }
        public System.DateTime cheque_date { get; set; }
        public decimal amount { get; set; }
        public int ledger_id { get; set; }
        public int party_id { get; set; }
        public string pdc_mode { get; set; }
        public string remarks { get; set; }
        public string cheque_status { get; set; }
        public System.DateTime updated_on { get; set; }
        public int status { get; set; }
    
        public virtual account_ledger account_ledger { get; set; }
        public virtual account_ledger account_ledger1 { get; set; }
        public virtual status status1 { get; set; }
    }
}
