//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class privileges
    {
        public int privilege_id { get; set; }
        public int user_id { get; set; }
        public int menu_id { get; set; }
        public int status { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual privilege_menu privilege_menu { get; set; }
        public virtual status status1 { get; set; }
    }
}
