//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_rawmaterial
    {
        public int production_rawmaterial_id { get; set; }
        public int production_id { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public decimal item_value { get; set; }
        public int status { get; set; }
    
        public virtual item item { get; set; }
        public virtual production production { get; set; }
        public virtual status status1 { get; set; }
    }
}
