//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_mapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production_mapping()
        {
            this.production_mapping_rowmaterial = new HashSet<production_mapping_rowmaterial>();
        }
    
        public int mapping_id { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public int total_rawmaterial { get; set; }
        public decimal total_value { get; set; }
        public int status { get; set; }
    
        public virtual item item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_mapping_rowmaterial> production_mapping_rowmaterial { get; set; }
        public virtual status status1 { get; set; }
    }
}
