//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase()
        {
            this.purchase_item = new HashSet<purchase_item>();
            this.purchase_order_item = new HashSet<purchase_order_item>();
        }
    
        public int purchase_id { get; set; }
        public System.DateTime purchase_date { get; set; }
        public string invoice_number { get; set; }
        public System.DateTime invoice_date { get; set; }
        public int vendor_id { get; set; }
        public Nullable<int> purchase_order { get; set; }
        public string payment_mode { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_no { get; set; }
        public decimal gross_amount { get; set; }
        public decimal total_discount { get; set; }
        public decimal total_beforevat { get; set; }
        public decimal total_vat { get; set; }
        public decimal roundup { get; set; }
        public decimal net_amount { get; set; }
        public decimal cash_paid { get; set; }
        public decimal balance_amount { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_item> purchase_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order_item> purchase_order_item { get; set; }
        public virtual status status1 { get; set; }
    }
}
