//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_return()
        {
            this.sales_return_item = new HashSet<sales_return_item>();
        }
    
        public int sales_return_id { get; set; }
        public System.DateTime sales_date { get; set; }
        public string sales_number { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> sales_order { get; set; }
        public string payment_mode { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_no { get; set; }
        public decimal gross_amount { get; set; }
        public decimal total_discount { get; set; }
        public decimal total_beforevat { get; set; }
        public decimal total_vat { get; set; }
        public decimal roundup { get; set; }
        public decimal net_amount { get; set; }
        public decimal cash_paid { get; set; }
        public decimal balance_amount { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_return_item> sales_return_item { get; set; }
        public virtual status status1 { get; set; }
        public virtual customer customer { get; set; }
    }
}
