//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_sale_compare
    {
        public Nullable<System.DateTime> saleDate { get; set; }
        public int customer_id { get; set; }
        public Nullable<decimal> saleAmount { get; set; }
    }
}
