//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_delivery_items_compare
    {
        public int delivery_id { get; set; }
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string route_name { get; set; }
        public System.DateTime delivery_date { get; set; }
        public Nullable<decimal> deliveryAmount { get; set; }
    }
}
