//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer_item
    {
        public int transfer_id { get; set; }
        public System.DateTime transfer_date { get; set; }
        public int employee_id { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public string transfer_type { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual item item { get; set; }
        public virtual status status1 { get; set; }
    }
}
