//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETask.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_log
    {
        public int log_id { get; set; }
        public string username { get; set; }
        public string module { get; set; }
        public string module_action { get; set; }
        public Nullable<System.DateTime> server_time { get; set; }
        public Nullable<int> reference_id { get; set; }
        public string summary { get; set; }
    }
}
