//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coupon()
        {
            this.coupon_leaf = new HashSet<coupon_leaf>();
        }
    
        public int coupon_id { get; set; }
        public string book_number { get; set; }
        public int leaf_from { get; set; }
        public int leaf_end { get; set; }
        public decimal leaf_rate { get; set; }
        public decimal book_rate { get; set; }
        public int leaf_count { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
        public int customer_id { get; set; }
        public System.DateTime issue_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coupon_leaf> coupon_leaf { get; set; }
        public virtual status status1 { get; set; }
        public virtual customer customer { get; set; }
    }
}
