//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_aggrement
    {
        public int customer_aggrement_id { get; set; }
        public int customer_id { get; set; }
        public int item_id { get; set; }
        public decimal max_qty { get; set; }
        public decimal unit_price { get; set; }
        public int status { get; set; }
        public int show_app { get; set; }
        public string serail_number { get; set; }
        public string remarks { get; set; }
    
        public virtual item item { get; set; }
        public virtual status status1 { get; set; }
        public virtual customer customer { get; set; }
    }
}
