//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.coupon = new HashSet<coupon>();
            this.customer_aggrement = new HashSet<customer_aggrement>();
            this.daily_collection = new HashSet<daily_collection>();
            this.delivery_items = new HashSet<delivery_items>();
            this.delivery_return = new HashSet<delivery_return>();
            this.purchase_order = new HashSet<purchase_order>();
            this.purchase = new HashSet<purchase>();
            this.purchase_return = new HashSet<purchase_return>();
            this.sales = new HashSet<sales>();
            this.sales_return = new HashSet<sales_return>();
            this.wallet_history = new HashSet<wallet_history>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string pobox { get; set; }
        public int customer_type { get; set; }
        public string remarks { get; set; }
        public string contact_person { get; set; }
        public string trn { get; set; }
        public int status { get; set; }
        public string wallet_number { get; set; }
        public Nullable<decimal> wallet_balance { get; set; }
        public Nullable<int> ledger_id { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<int> route_id { get; set; }
        public int cloud_sync { get; set; }
        public string payment_mode { get; set; }
        public string delivery_interval { get; set; }
        public Nullable<System.DateTime> added_time { get; set; }
        public Nullable<int> customer_temp_id { get; set; }
        public Nullable<int> building_id { get; set; }
        public Nullable<int> salesman_ledger { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> new_customer { get; set; }
        public decimal credit_limit { get; set; }
    
        public virtual account_ledger account_ledger { get; set; }
        public virtual building building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coupon> coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_aggrement> customer_aggrement { get; set; }
        public virtual route route { get; set; }
        public virtual status status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daily_collection> daily_collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_items> delivery_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_return> delivery_return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_return> purchase_return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales> sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_return> sales_return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wallet_history> wallet_history { get; set; }
        public virtual employee employee { get; set; }
    }
}
