//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class default_values
    {
        public int type_id { get; set; }
        public string type_name { get; set; }
        public Nullable<int> type_value { get; set; }
        public Nullable<int> status { get; set; }
    }
}
