//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public delivery()
        {
            this.daily_collection = new HashSet<daily_collection>();
            this.delivery_item_summary = new HashSet<delivery_item_summary>();
            this.delivery_items = new HashSet<delivery_items>();
            this.sales = new HashSet<sales>();
        }
    
        public int delivery_id { get; set; }
        public System.DateTime delivery_date { get; set; }
        public int employee_id { get; set; }
        public string vehicle_no { get; set; }
        public string delivery_route { get; set; }
        public Nullable<int> route_id { get; set; }
        public int customer_count { get; set; }
        public Nullable<decimal> gross_amount { get; set; }
        public decimal total_discount { get; set; }
        public decimal total_beforevat { get; set; }
        public decimal total_vat { get; set; }
        public decimal net_amount { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
        public string helper { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daily_collection> daily_collection { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_item_summary> delivery_item_summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_items> delivery_items { get; set; }
        public virtual route route { get; set; }
        public virtual status status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales> sales { get; set; }
    }
}
