//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_serial
    {
        public int document_id { get; set; }
        public string document_type { get; set; }
        public string prefix { get; set; }
        public int next_number { get; set; }
        public int status { get; set; }
    
        public virtual status status1 { get; set; }
    }
}
