//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.customer_aggrement = new HashSet<customer_aggrement>();
            this.delivery_item_summary = new HashSet<delivery_item_summary>();
            this.delivery_items = new HashSet<delivery_items>();
            this.delivery_return = new HashSet<delivery_return>();
            this.item_damage = new HashSet<item_damage>();
            this.item_return_exception = new HashSet<item_return_exception>();
            this.item_return_exception1 = new HashSet<item_return_exception>();
            this.item_transaction = new HashSet<item_transaction>();
            this.production = new HashSet<production>();
            this.production_mapping_rowmaterial = new HashSet<production_mapping_rowmaterial>();
            this.production_mapping = new HashSet<production_mapping>();
            this.production_rawmaterial = new HashSet<production_rawmaterial>();
            this.purchase_item = new HashSet<purchase_item>();
            this.purchase_order_item = new HashSet<purchase_order_item>();
            this.purchase_return_item = new HashSet<purchase_return_item>();
            this.sales_item = new HashSet<sales_item>();
            this.sales_return_item = new HashSet<sales_return_item>();
            this.transfer_item = new HashSet<transfer_item>();
        }
    
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string barcode { get; set; }
        public string brand { get; set; }
        public int uom { get; set; }
        public int tax { get; set; }
        public string description { get; set; }
        public decimal cost { get; set; }
        public decimal purchase_rate { get; set; }
        public decimal sale_rate { get; set; }
        public decimal opening_stock { get; set; }
        public int rawmeterial { get; set; }
        public int sellable { get; set; }
        public int stockable { get; set; }
        public int status { get; set; }
        public decimal Stock { get; set; }
        public decimal godown_stock { get; set; }
        public Nullable<int> sale_ledger { get; set; }
        public Nullable<int> purchase_ledger { get; set; }
        public int agreement_item { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_aggrement> customer_aggrement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_item_summary> delivery_item_summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_items> delivery_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_return> delivery_return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_damage> item_damage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_return_exception> item_return_exception { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_return_exception> item_return_exception1 { get; set; }
        public virtual status status1 { get; set; }
        public virtual tax_setting tax_setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_transaction> item_transaction { get; set; }
        public virtual uom_setting uom_setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production> production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_mapping_rowmaterial> production_mapping_rowmaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_mapping> production_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_rawmaterial> production_rawmaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_item> purchase_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order_item> purchase_order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_return_item> purchase_return_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_item> sales_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_return_item> sales_return_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfer_item> transfer_item { get; set; }
        public virtual account_ledger account_ledger { get; set; }
        public virtual account_ledger account_ledger1 { get; set; }
    }
}
