//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_return_exception
    {
        public int return_id { get; set; }
        public int item_id { get; set; }
        public int return_item_id { get; set; }
        public int status { get; set; }
    
        public virtual item item { get; set; }
        public virtual item item1 { get; set; }
        public virtual status status1 { get; set; }
    }
}
