//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_damage
    {
        public int item_damage_id { get; set; }
        public System.DateTime damage_date { get; set; }
        public int item_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public decimal qty { get; set; }
        public decimal cost { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
        public int item_id_damaged { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual item item { get; set; }
        public virtual status status1 { get; set; }
    }
}
