//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger_mapping
    {
        public int ledger_mapping_id { get; set; }
        public string ledger_type { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> ledger_id { get; set; }
        public int status { get; set; }
    
        public virtual account_group account_group { get; set; }
        public virtual account_ledger account_ledger { get; set; }
        public virtual status status1 { get; set; }
    }
}
