//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class production
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production()
        {
            this.production_rawmaterial = new HashSet<production_rawmaterial>();
        }
    
        public int production_id { get; set; }
        public System.DateTime production_date { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public decimal cost { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
    
        public virtual item item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_rawmaterial> production_rawmaterial { get; set; }
        public virtual status status1 { get; set; }
    }
}
