//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_item
    {
        public int purchase_item_id { get; set; }
        public int purchase_id { get; set; }
        public int item_id { get; set; }
        public decimal qty { get; set; }
        public decimal rate { get; set; }
        public decimal gross_amount { get; set; }
        public decimal discount { get; set; }
        public decimal total_beforevat { get; set; }
        public decimal vat_amount { get; set; }
        public decimal net_amount { get; set; }
        public int status { get; set; }
    
        public virtual item item { get; set; }
        public virtual purchase purchase { get; set; }
        public virtual status status1 { get; set; }
    }
}
