//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BETaskSync.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet_history
    {
        public int wallet_history_id { get; set; }
        public string wallet_number { get; set; }
        public int customer_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date { get; set; }
        public string recharge_by { get; set; }
        public string payment_mode { get; set; }
        public string remarks { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
